import type { ClientType } from "../../db/schema";

export const fakeClients: ClientType[] = [
  {
    id: 1,
    name: "João Silva",
    document: "12345678901",
    type_client: "Nacional",
    notes: null,
  },
  {
    id: 2,
    name: "Maria Oliveira",
    document: "987.654.321-00",
    type_client: "Nacional",
    notes: "Cliente recorrente",
  },
  {
    id: 3,
    name: "Carlos Pereira",
    document: "11222333000181",
    type_client: "Nacional",
    notes: null,
  },
  {
    id: 4,
    name: "Ana Souza",
    document: "45.678.912/0001-09",
    type_client: "Nacional",
    notes: "Prefere contato por email",
  },
  {
    id: 5,
    name: "Pedro Lima",
    document: "32165498700",
    type_client: "Nacional",
    notes: null,
  },
  {
    id: 6,
    name: "Fernanda Rocha",
    document: "55.444.333/0001-22",
    type_client: "Nacional",
    notes: "Contrato anual",
  },
  {
    id: 7,
    name: "Lucas Martins",
    document: "74185296310",
    type_client: "Nacional",
    notes: null,
  },
  {
    id: 8,
    name: "Empresa Alpha LTDA",
    document: "12.345.678/0001-90",
    type_client: "Nacional",
    notes: "Pessoa jurídica",
  },
  {
    id: 9,
    name: "Ricardo Nunes",
    document: "15935745682",
    type_client: "Nacional",
    notes: null,
  },
  {
    id: 10,
    name: "Juliana Costa",
    document: "98.765.432/0001-11",
    type_client: "Nacional",
    notes: "Primeira compra",
  },
  {
    id: 11,
    name: "Bruno Azevedo",
    document: "45678912355",
    type_client: "Nacional",
    notes: null,
  },
  {
    id: 12,
    name: "Empresa Beta SA",
    document: "66778899000144",
    type_client: "Nacional",
    notes: "Cliente corporativo",
  },
  {
    id: 13,
    name: "Patrícia Mendes",
    document: "852.963.741-20",
    type_client: "Nacional",
    notes: null,
  },
  {
    id: 14,
    name: "Rafael Teixeira",
    document: "14725836900",
    type_client: "Nacional",
    notes: "Aguardando retorno",
  },
  {
    id: 15,
    name: "Comercial Gamma ME",
    document: "22.333.444/0001-55",
    type_client: "Nacional",
    notes: null,
  },
];
